baseURL = "https://test.docbits.com"
languageCode = "en-us"
title = "DocBits"
theme = "docbits"

# Direct Hugo to the Quasar build directory for static files
publishDir = "dist/spa"

[params]
  # Custom cache control for specific asset types
  cache_control_static = "public, max-age=31536000, immutable"
  cache_control_html = "no-cache, must-revalidate"

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  page = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

# Cache control for HTML files
[outputFormats.HTML]
  mediaType = "text/html"
  rel = "canonical"
  cacheControl = "no-cache, must-revalidate"

# Cache control for CSS
[mediaTypes."text/css"]
  cacheControl = "public, max-age=1209600, s-maxage=86400, immutable"

# Cache control for JavaScript
[mediaTypes."application/javascript"]
  cacheControl = "public, max-age=1209600, s-maxage=86400, immutable"

# Cache control for images (PNG, JPG, etc.)
[mediaTypes."image/png"]
  cacheControl = "public, max-age=1209600, s-maxage=86400, immutable"
[mediaTypes."image/jpeg"]
  cacheControl = "public, max-age=1209600, s-maxage=86400, immutable"
[mediaTypes."image/svg+xml"]
  cacheControl = "public, max-age=1209600, s-maxage=86400, immutable"

# Cache control for fonts
[mediaTypes."font/woff"]
  cacheControl = "public, max-age=1209600, s-maxage=86400, immutable"
[mediaTypes."font/woff2"]
  cacheControl = "public, max-age=1209600, s-maxage=86400, immutable"
